# .github/workflows/release.yaml

name: GoReleaser Build and Release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*.*.*' # Trigger workflow only when tags matching v*.*.* (e.g., v0.1.0, v1.2.3) are pushed

# Specifies permissions needed for the job
permissions:
  contents: write # Allow actions to write to the repository (e.g., create releases, upload assets)

jobs:
  # Define the job ID (can be anything)
  goreleaser:
    # Specify the runner type
    runs-on: ubuntu-latest

    # Define the sequence of tasks that make up the job
    steps:
      # Step 1: Check out the repository's code at the specific tag
      - name: Checkout Code
        uses: actions/checkout@v4 # Use the official checkout action (latest major version)
        with:
          fetch-depth: 0 # Fetch all history so GoReleaser can generate changelogs based on commits

      # Step 2: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5 # Use the official Go setup action
        with:
          go-version: '1.21' # Specify the Go version your project uses (or use 'stable')
          cache: true # Enable Go build caching

      # Step 3: Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5 # Use the official GoReleaser action
        with:
          # Specify the GoReleaser version to use
          version: latest # <-- Make sure this line is uncommented
          # Arguments to pass to GoReleaser
          args: release --clean
        env:
          # GITHUB_TOKEN is automatically created by GitHub Actions and passed to GoReleaser
          # The 'permissions: contents: write' setting above grants it the necessary rights
          # for creating releases in *this* repository.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # === IMPORTANT for Homebrew Tap ===
          # If your Homebrew tap repository (homebrew-git-util) is separate and public,
          # the default GITHUB_TOKEN *might* not have permission to push to it.
          # The recommended way is to:
          # 1. Create a *new* Personal Access Token (Classic) with only 'public_repo' scope.
          # 2. Add this token as a Secret in your git-util repository settings
          #    (Settings -> Secrets and variables -> Actions -> New repository secret). Name it e.g., HOMEBREW_TAP_TOKEN.
          # 3. Uncomment the line below in this workflow file.
          # 4. Add/Uncomment the 'token' line in the 'brews.repository' section of your .goreleaser.yaml:
          #    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}" # Matches env var below
          #
          # HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
