# .github/workflows/release.yaml

name: GoReleaser Build and Release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*.*.*' # Trigger workflow only when tags matching v*.*.* (e.g., v0.1.0, v1.2.3) are pushed

# Specifies permissions needed for the job
permissions:
  contents: write # Allow actions to write to the repository (e.g., create releases, upload assets)

jobs:
  # Define the job ID (can be anything)
  goreleaser:
    # Specify the runner type
    runs-on: ubuntu-latest

    # Define the sequence of tasks that make up the job
    steps:
      # Step 1: Check out the repository's code at the specific tag
      - name: Checkout Code
        uses: actions/checkout@v4 # Use the official checkout action (latest major version)
        with:
          fetch-depth: 0 # Fetch all history so GoReleaser can generate changelogs based on commits

      # Step 2: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5 # Use the official Go setup action
        with:
          go-version: '1.21' # Specify the Go version your project uses (or use 'stable')
          cache: true # Enable Go build caching

      # Step 3: Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5 # Use the official GoReleaser action
        with:
          # Specify the GoReleaser version to use
          version: v2.0.1 # Use a specific v2 version
          # Arguments to pass to GoReleaser
          args: release --clean
        env:
          # GITHUB_TOKEN is automatically created by GitHub Actions and passed to GoReleaser
          # The 'permissions: contents: write' setting above grants it the necessary rights
          # for creating releases in *this* repository.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # === IMPORTANT for Homebrew Tap ===
          # Pass the dedicated Homebrew tap token (stored as a secret) as an environment variable.
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }} # <-- Ensure this line is UNCOMMENTED
